# Generated by Django 5.0.6 on 2024-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Walkly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Us',
        ),
        migrations.RenameModel(
            old_name='Feature',
            new_name='Features',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='profession_name',
            field=models.CharField(default='Traniner', max_length=100),
            preserve_default=False,
        ),
    ]
